leanix:
  base-url: https://${LEANIX_DOMAIN}/services
  heartbeat:
    interval: ${LEANIX_HEARTBEAT_INTERVAL:300000} #  5 minutes
  vsm:
    connector:
      api-user-token: ${LEANIX_TECHNICAL_USER_TOKEN}
    events-broker:
      base-url: ${leanix.vsm.base-url}/vsm-events-broker
    auth:
      access-token-uri: ${leanix.base-url}/mtm/v1
  gitlab:
    base-url: ${GITLAB_URL}
    access-token: ${GITLAB_TOKEN}
    webhook-url: ${GITLAB_WEBHOOK_URL}
    leanix-id: ${LEANIX_ID}

server:
  port: 8082
