leanix:
  base-url: http://localhost:8080
  heartbeat:
    interval: ${LEANIX_HEARTBEAT_INTERVAL:300000} #  5 minutes
  vsm:
    events-broker:
      base-url: http://localhost:8080
    auth:
      access-token-uri: https://test-app-1.leanix.net/services/mtm/v1

server:
  port: 8082
