leanix:
  base-url: http://localhost:8081
  heartbeat:
    interval: ${LEANIX_HEARTBEAT_INTERVAL:300000} #  5 minutes
  vsm:
    events-broker:
      base-url: http://localhost:8083
    auth:
      access-token-uri: https://test-app-1.leanix.net/services/mtm/v1
  gitlab:
    leanix-id: ${LEANIX_ID:dummy}

server:
  port: 8082
