leanix:
  base-url: http://localhost:8081
  heartbeat:
    interval: ${LEANIX_HEARTBEAT_INTERVAL:300000} #  5 minutes
  vsm:
    events-broker:
      base-url: ${EVENT_BROKER_BASE_URL:http://localhost:8083}
    auth:
      access-token-uri: https://test-app-1.leanix.net/services/mtm/v1
  gitlab:
    webhook-url: ${GITLAB_WEBHOOK_URL:dummy}
    webhook-enable-ssl-verification: ${ENABLE_WEBHOOK_SSL:false}

server:
  port: 8082
