leanix:
  base-url: https://${LEANIX_DOMAIN}/services
  heartbeat:
    interval: ${LEANIX_HEARTBEAT_INTERVAL:300000} #  5 minutes
  vsm:
    base-url: ${leanix.base-url}/vsm-canopy/v1
    connector:
      api-user-token: ${LEANIX_TECHNICAL_USER_TOKEN}
      gitlab-token: ${GITLAB_TOKEN}
      gitlab-url: ${GITLAB_URL}
    events-broker:
      base-url: ${leanix.vsm.base-url}/vsm-events-broker
    auth:
      access-token-uri: ${leanix.base-url}/mtm/v1
    dora:
      total-days: ${DORA_PERIOD_IN_DAYS:30}
  gitlab:
    webhook-url: ${GITLAB_WEBHOOK_URL:}
    webhook-enable-ssl-verification: ${ENABLE_WEBHOOK_SSL:true}

server:
  port: 8082
